title: CurvaEnAragón | Evolución de la crisis sanitaria del COVID-19 o Coronavirus en Aragón
description: >- 
  Conoce la evolución del coronavirus o COVID-19 en Aragón. También en Huesca, Zaragoza y Teruel.
  Actualizaciones diarias basados en los datos oficiales facilitados por el Gobierno de Aragón.


# Build settings
markdown: kramdown