title: La curva en Aragón
email: dani@danilat.com
description: >- 
  Intento de facilitar la visualización de información de la evolución del coronavirus o COVID-19 en Aragón.


# Build settings
markdown: kramdown