title: CurvaEnAragón | Evolución de la curva en Aragón
description: >- 
  Visualización que facilita la conocer en interpretar la evolución del coronavirus o COVID-19 en Aragón. También en Huesca, Zaragoza y Teruel.
  Actualizaciones diarias usando los datos oficiales facilitados por el Gobierno de Aragón a partir Aragón Open Data.


# Build settings
markdown: kramdown