title: CurvaEnAragón | Evolución de la crisis sanitaria del COVID-19 o Coronavirus en Aragón
description: >- 
  Visualiza la evolución de coronavirus (COVID-19) en Aragón. Conoce la situación en Huesca, Zaragoza y Teruel.
  Actualizaciones diarias. Datos oficiales facilitados por el Gobierno de Aragón (Aragón Open Data).


# Build settings
markdown: kramdown