name: Send notifications to telegram

on:
  push:
    paths:
    - '_data/last_update'

jobs:
  telegram_job:
    runs-on: ubuntu-latest
    name: A job to launch telegram notifications
    steps:
    - name: Send notifications
      id: send_notificsations
      uses: danilat/externalized-telegram-notifications-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_KEY }}
        content-url: 'https://raw.githubusercontent.com/danilat/covid-19-aragon/master/_data/changelog_message'